export const categories = ['All Sports', 'Basketball', 'Football', 'Baseball', 'Boxing']
export const eras = ['70s', '80s', '90s', '00s']

export const channels = [
  {
    id: 'nba-archive',
    number: 21,
    name: 'NBA Archive',
    sport: 'Basketball',
    era: '90s',
    channelId: 'UCT76eft4Isa6-f5RlHMqYFg',
    videoId: 'bvPIAWOI75k',
    title: 'Classic Basketball Archive',
    blurb: 'Rare games, finishes, and hardwood time capsules.',
  },
  {
    id: 'mdbball',
    number: 22,
    name: 'MDBBall',
    sport: 'Basketball',
    era: '90s',
    channelId: 'UCAGDKi1a7nRlcxUKtBh7sDg',
    videoId: 'o5lWDUeyatI',
    title: 'Rockets @ Lakers — March 1996',
    blurb: 'Retro NBA broadcasts, highlights, plays, and moments.',
  },
  {
    id: 'old-school-buckets',
    number: 23,
    name: 'Old School Buckets',
    sport: 'Basketball',
    era: '00s',
    channelId: 'UCBhuDLX65jj5BUxo8Iphixw',
    videoId: 'p0tbMJKY2RQ',
    title: '1990 NBA All-Star Game',
    blurb: 'Full games and deep cuts from a golden hoops era.',
  },
  {
    id: '1990s-sports-home',
    number: 24,
    name: '1990s Sports Home',
    sport: 'Basketball',
    era: '90s',
    channelId: 'UC8yPlbAm8F5vJyPeA9lhy8A',
    videoId: 'bM9A3nt6j4U',
    title: '1998 Finals — Game 4',
    blurb: 'The decade when sports became appointment television.',
  },
  {
    id: 'channel-23',
    number: 25,
    name: 'Channel 23',
    fullName: 'Channel 23: The Complete Michael Jordan Archive',
    sport: 'Basketball',
    era: '80s',
    channelId: 'UCr7NbqZBBl0_83HUqoTvE1w',
    videoId: 'ItCRdBf5SxA',
    title: 'Mavericks vs Bulls — March 1987',
    blurb: 'A complete-player archive built for all-time hoops fans.',
  },
  {
    id: 'kevin-smith',
    number: 26,
    name: 'Kevin Smith',
    sport: 'Football',
    era: '00s',
    channelId: 'UCwZuFECdVBeqO499Nlmim_Q',
    videoId: 'LR1coSRYExY',
    title: 'Saints vs 49ers — 1982',
    blurb: 'Full-game NFL recordings and fan-preserved broadcasts.',
  },
  {
    id: 'survivor-504',
    number: 27,
    name: 'Survivor504',
    sport: 'Football',
    era: '90s',
    channelId: 'UCOHCk10JiMYRQuqYTPykkPg',
    videoId: 'PNMx0w8CQ6c',
    title: '1990 NFC Championship Game',
    blurb: 'Classic football broadcasts from the tape shelf.',
  },
  {
    id: '80s-football-cards',
    number: 28,
    name: '80s Football Cards',
    sport: 'Football',
    era: '80s',
    channelId: 'UC7Qzmo0nl0SStk9OKoKGjMQ',
    videoId: 'ALClwnQIlQk',
    title: '1984 MNF — Bears vs Chargers',
    blurb: 'Old broadcasts with the texture of a treasured card box.',
  },
  {
    id: 'nfl-x-files',
    number: 29,
    name: 'NFL X FILES',
    sport: 'Football',
    era: '70s',
    channelId: 'UCZhszUtK2i4VE2k5fWYRpIg',
    videoId: 'DcQFoSr07QM',
    title: 'Larry Brown — 1972 NFL MVP',
    blurb: 'Football stories, lost tape, and legends under review.',
  },
  {
    id: 'dave-volsky',
    number: 30,
    name: 'Dave Volsky',
    sport: 'Football',
    era: '70s',
    channelId: 'UCn7DglXcVTblAf4kufxXGOg',
    videoId: '9NH4SuTTifI',
    title: 'The Craig Morton Story — Part 1',
    blurb: 'Long-form football history and documentary profiles.',
  },
  {
    id: 'pro-football-daily',
    number: 31,
    name: 'Pro Football Daily',
    sport: 'Football',
    era: '70s',
    channelId: 'UCbZTUn3VYSX8Jbvz2S47Omw',
    videoId: 'BZvk0FGBpPs',
    title: 'SportsCentury — Joe Namath',
    blurb: 'Pro football history, daily from the archives.',
  },
  {
    id: '4k-boxing',
    number: 32,
    name: '4K BOXING',
    sport: 'Boxing',
    era: '90s',
    channelId: 'UCH89_C9Dp7w85XSHdq_0dbw',
    videoId: '6rHPtJNfbAM',
    title: 'De La Hoya vs Carr — Highlights',
    blurb: 'Classic fights restored with modern clarity.',
  },
  {
    id: 'sterling-wainscott',
    number: 33,
    name: 'Sterling Wainscott',
    sport: 'Boxing',
    era: '80s',
    channelId: 'UCoyJ0zmMFd7LZwK6hON6QnQ',
    videoId: 'YIVzmPWuL24',
    title: "HBO Boxing's Greatest Hits — 1989",
    blurb: 'Full-program fight nights preserved from the tape era.',
  },
  {
    id: 'classic-boxing',
    number: 34,
    name: 'Classic Boxing Matches',
    sport: 'Boxing',
    era: '80s',
    channelId: 'UC7JmxzLn27bQ1XrST0XtfeA',
    videoId: '9zMR-PJSffg',
    title: 'Joe Louis vs James J. Braddock',
    blurb: 'Historic championship rounds and forgotten knockouts.',
  },
  {
    id: 'classic-mlb',
    number: 35,
    name: 'Classic MLB',
    sport: 'Baseball',
    era: '80s',
    channelId: 'UC5Aqied-buV601O_HfLqG2A',
    videoId: 'Z68mzMaM1NI',
    title: '1980 NL West Playoff',
    blurb: 'Full games and rare innings from baseball history.',
  },
  {
    id: 'larrys-classic-sports',
    number: 36,
    name: "Larry's Classic Sports",
    sport: 'All Sports',
    era: '80s',
    channelId: 'UCbBA0ybji3HvujNJPQZIa7g',
    videoId: 'p3WBB1IhR3s',
    title: 'Classic Sports Rewind',
    blurb: 'A deep, eclectic shelf of vintage sports programming.',
  },
  {
    id: 'find-baseball',
    number: 37,
    name: 'This Is Where You Find Baseball',
    sport: 'Baseball',
    era: '00s',
    channelId: 'UChcXJBA7jI8PtvXTKUgIEgQ',
    videoId: 'VUNdxvCePhk',
    title: 'Cardinals vs Reds — August 2010',
    blurb: 'Full broadcasts for people who never skip the middle innings.',
  },
  {
    id: 'joeydbball',
    number: 38,
    name: 'joeydbball',
    sport: 'Baseball',
    era: '80s',
    channelId: 'UC4Ell6aDksbFSwRg4J4EPdQ',
    videoId: 'INoBmxv9G8Y',
    title: 'Barry Bonds at Bat — April 1988',
    blurb: 'Baseball moments preserved exactly as fans remember them.',
  },
  {
    id: 'phenia-films',
    number: 39,
    name: 'Phenia Films',
    fullName: 'Phenia Films SPORTS CHANNEL REWIND',
    sport: 'All Sports',
    era: '80s',
    channelId: 'UCtzrZVVUNKEKgsikfKtBjRw',
    videoId: 'x4Gz1FmcS8A',
    title: 'Houston Summit at Philadelphia Fever — 1980',
    blurb: 'Original broadcasts, obscure leagues, and beautiful analog tape.',
  },
  {
    id: 'mjsiii',
    number: 40,
    name: 'MJSIII',
    sport: 'Football',
    era: '90s',
    channelId: 'UCr8HSfSxZ_Sp6v_NCWZUR2Q',
    videoId: 'xm7KwSIS-As',
    title: '1983 Cowboys at Vikings',
    blurb: 'Full vintage NFL broadcasts from one of football’s deepest tape libraries.',
  },
]

export const getChannelUrl = (channel) => `https://www.youtube.com/channel/${channel.channelId}`
export const getUploadsPlaylist = (channel) => `UU${channel.channelId.slice(2)}`
export const getUploadsUrl = (channel) => `https://www.youtube.com/playlist?list=${getUploadsPlaylist(channel)}`
export const getThumb = (channel) => `https://i.ytimg.com/vi/${channel.videoId}/hqdefault.jpg`
